### ISSUE TITLE
Request for some improvements

### ISSUE THREAD

**Issue by dkaledin** [theboss9976/nextjs-ecommerce#1]
### Code
1. You should use `getServerSideProps ` instead `getStaticProps` because we have dynamic data.
1. You should use package `@types/react-paginate` instead this declaration `typings/react-paginate.d.ts`
2. Directories like `types` calls `interfaces`, usually.
3. You can separate page files to the few files. For example: `pages/products.tsx`, `component/products/products.tsx`, `component/products/products.interface.ts`, `component/products/products.style.ts` and even files `component/products/products.service.ts` that will contain `getServerProps` function.
4. The `api.ts` uses native `fetch` in each method. It can be problem if we will want to add some common behavior for `fetch`, for example some common header or common query param. Better way is using wrapped `fetch`. I mean to move `fetch` in the separate method.

----

### Functionality 
1. Product description should be decoded.
2. You should use `$` for prices, and use field `special` from `product` when it not empty, and `price` when `special` is empty.
3. Products in the cart should be remained after refreshing page.
4. We have to save SEO options in the pagination.

**Comment by theboss9976** [comment]
Hey @dkaledin I just updated the project and fixed all notes.

About the **fifth point of Code** - I found a **wretch** package https://github.com/elbywan/wretch. It has clean methods and it a wrapper for the native **fetch** function

About the **third point of Functionality** - I used localStorage like a mock of database

About the **fourth point of Functionality** - I updated the URL of the **products** page with query params like `?page=2` when click to the pagination buttons. I think usually a website has a sitemap file with all URLs for the search spiders like Google Search, so via the sitemap file the spider will be able to open pages and scan all content
